### ISSUE TITLE
a2s fails to run currently

### ISSUE THREAD

**Issue by snecklifter** [Schoonology/node-a2s#1]
I get the following error:

Not enough non-option arguments: got 0, need at least 1

**Comment by Schoonology** [comment]
Can I get a little more context? How did you install and run this script?

**Comment by snecklifter** [comment]
@Schoonology just with npm install. It looks like api.a2saas.com doesn't exist any more anyway?

**Comment by Schoonology** [comment]
Would you look at that. 😞

I'll archive this repo and deprecate the npm package. Thanks, @snecklifter , for bringing that up.
